AUTOLOGIN_VERSION = $(LOGIN_NG_VERSION)
AUTOLOGIN_LICENSE = GPL-2.0-or-later
AUTOLOGIN_SITE = $(call github,NeroReflex,login-ng,$(AUTOLOGIN_VERSION))
AUTOLOGIN_DEPENDENCIES = host-rustc
AUTOLOGIN_SUBDIR = login_ng-ctl
AUTOLOGIN_INSTALL_STAGING = YES

define AUTOLOGIN_STORE_USER_PASSWORD
	echo "${BR2_EQ_AUTOLOGIN_USER}" > $(TARGET_DIR)/user_autologin_pw
	echo "${BR2_EQ_AUTOLOGIN_USER}"
	exit -1
endef

AUUTOLOGIN_POST_INSTALL_STAGING_HOOKS += AUTOLOGIN_STORE_USER_PASSWORD

$(eval $(host-cargo-package))
