QTQUICKDESIGNER_COMPONENTS_LICENSE = GPL-3.0
QTQUICKDESIGNER_COMPONENTS_VERSION = qds-dev-4.7
QTQUICKDESIGNER_COMPONENTS_SITE = $(call github,qt-labs,qtquickdesigner-components,$(QTQUICKDESIGNER_COMPONENTS_VERSION))
QTQUICKDESIGNER_COMPONENTS_SITE_METHOD = git
QTQUICKDESIGNER_COMPONENTS_DEPENDENCIES = qt6base qt6declarative host-pkgconf
QTQUICKDESIGNER_COMPONENTS_INSTALL_STAGING = YES
QTQUICKDESIGNER_COMPONENTS_INSTALL_TARGET = YES

$(eval $(cmake-package))
