VARISCITE_VERSION = v0.1
VARISCITE_SITE_METHOD = local
VARISCITE_SITE = ${BR2_EXTERNAL_EMBEDDED_QUICKSTART_PATH}/package/variscite
VARISCITE_INSTALL_TARGET = YES

define VARISCITE_INSTALL_GPIOCHIP
	$(INSTALL) -D -m 644 $(@D)/gpiochip $(TARGET_DIR)/etc/gpiochip
endef

VARISCITE_POST_INSTALL_TARGET_HOOKS += VARISCITE_INSTALL_GPIOCHIP

$(eval $(generic-package))
