RUST_COREUTILS_VERSION = 0.0.29
RUST_COREUTILS_LICENSE = MIT
RUST_COREUTILS_SITE = $(call github,uutils,coreutils,$(RUST_COREUTILS_VERSION))
RUST_COREUTILS_DEPENDENCIES = host-rustc
#RUST_COREUTILS_INSTALL_STAGING = YES

#define LOGIN_NG_CTL_POST_INSTALL
#	$(INSTALL) -D -m 644 $(BR2_EXTERNAL_EMBEDDED_QUICKSTART_PATH)/package/login_ng-ctl/login_ng-ctl.pam \
#		$(TARGET_DIR)/etc/pam.d/login_ng-ctl
#endef
#
#LOGIN_NG_CTL_POST_INSTALL_TARGET_HOOKS += LOGIN_NG_CTL_POST_INSTALL

$(eval $(cargo-package))
