# Auto-Generated by cargo-bitbake 0.3.16
#
inherit cargo

# If this is git based prefer versioned ones if they exist
# DEFAULT_PREFERENCE = "-1"

SRC_URI += "git://github.com/NeroReflex/pam_polyauth.git;protocol=https;nobranch=1;branch=main"
SRCREV = "${PV}"
S = "${WORKDIR}/git"
CARGO_SRC_DIR = ""

DEPENDS = "libpam"

inherit features_check
REQUIRED_DISTRO_FEATURES = "pam"

SUMMARY = "Additional pam module and service to login the user."
HOMEPAGE = "https://github.com/NeroReflex/pam_polyauth"

LICENSE = "GPL-2.0-or-later"
LIC_FILES_CHKSUM = " \
    file://LICENSE.md;md5=83ea31b4ebf7c17dcd4f18612a0b1df4 \
"

do_compile:append () {
    export RUSTFLAGS="${RUSTFLAGS}"

    bbnote "Using rust targets from ${RUST_TARGET_PATH}"
    bbnote "cargo = $(which ${CARGO})"
    bbnote "${CARGO} build ${CARGO_BUILD_FLAGS} $@"
    "${CARGO}" build ${CARGO_BUILD_FLAGS} "$@"
}

do_install:append () {
    install -d ${D}/${libdir}/security/
    install ${B}/target/${CARGO_TARGET_SUBDIR}/libpam_polyauth.so ${D}/${libdir}/security/pam_polyauth.so

    install -d ${D}/usr/share/dbus-1/system.d/
    install -D -m 644 ${S}/rootfs/usr/share/dbus-1/system.d/org.neroreflex.polyauth_mount.conf \
        ${D}${datadir}/dbus-1/system.d/org.neroreflex.polyauth_mount.conf
    install -D -m 644 ${S}/rootfs/usr/share/dbus-1/system.d/org.neroreflex.polyauth_session.conf \
        ${D}${datadir}/dbus-1/system.d/org.neroreflex.polyauth_session.conf

    install -d ${D}${systemd_unitdir}/system
    install -Dm644 ${S}/rootfs/usr/lib/systemd/system/pam_polyauth.service ${D}${systemd_unitdir}/system/pam_polyauth.service

    install -d ${D}${datadir}/bash-completion/completions/
    install -Dm644 ${S}/completions/polyauthctl.bash ${D}${datadir}/bash-completion/completions/polyauthctl

    install -d ${D}${sysconfdir}/systemd/system/multi-user.target.wants
    ln -sf ${systemd_unitdir}/system/pam_polyauth.service \
        ${D}${sysconfdir}/systemd/system/multi-user.target.wants/pam_polyauth.service
}

FILES:${PN} += " \
    ${libdir}/security/pam_polyauth.so \
    ${datadir}/dbus-1/system.d/org.neroreflex.polyauth_mount.conf \
    ${datadir}/dbus-1/system.d/org.neroreflex.polyauth_session.conf \
    ${systemd_unitdir}/system/pam_polyauth.service \
    ${datadir}/bash-completion/completions/polyauthctl \
"

# includes this file if it exists but does not fail
# this is useful for anything you may want to override from
# what cargo-bitbake generates.
include pam-polyauth-${PV}.inc
include pam-polyauth.inc

# include cargo dependencies
include dependencies.inc
include dependencies_${PV}.inc
