ATOMROOTFSINIT_VERSION = 0.6.13
ATOMROOTFSINIT_LICENSE = GPL-2.0-or-later
ATOMROOTFSINIT_SOURCE = $(ATOMROOTFSINIT_VERSION).tar.gz
ATOMROOTFSINIT_SITE = https://github.com/NeroReflex/atomrootfsinit/archive/refs/tags
ATOMROOTFSINIT_DEPENDENCIES = host-rustc
ATOMROOTFSINIT_INSTALL_STAGING = YES
#ATOMROOTFSINIT_CARGO_BUILD_OPTS = --all-features
#ATOMROOTFSINIT_CARGO_INSTALL_OPTS = --all-features

$(eval $(cargo-package))
