ATOMROOTFSINIT_VERSION = 0.5.0
ATOMROOTFSINIT_LICENSE = GPL-2.0-or-later
ATOMROOTFSINIT_SOURCE = $(ATOMROOTFSINIT_VERSION).tar.gz
ATOMROOTFSINIT_SITE = https://github.com/NeroReflex/atomrootfsinit/archive/refs/tags
ATOMROOTFSINIT_DEPENDENCIES = host-rustc
ATOMROOTFSINIT_INSTALL_STAGING = YES
ATOMROOTFSINIT_CARGO_BUILD_OPTS = --all-features
ATOMROOTFSINIT_CARGO_INSTALL_OPTS = --all-features

define ATOMROOTFSINIT_CREATE_SYSROOT_DIR
	$(shell mkdir -p ${TARGET_DIR}/sysroot)
endef

define ATOMROOTFSINIT_POST_INSTALL
	$(shell ln -sf /usr/bin/atomrootfsinit ${TARGET_DIR}/usr/bin/init)
endef

ATOMROOTFSINIT_POST_INSTALL_POST_INSTALL_TARGET_HOOKS += ATOMROOTFSINIT_POST_INSTALL ATOMROOTFSINIT_CREATE_SYSROOT_DIR

$(eval $(cargo-package))
